version: '3'
services:
  api:
    container_name: api_container
    build:
      context: ./
      args:
        NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/app/src
      - ./nest-cli.json:/app/nest-cli.json
      - ./node_modules:/app/node_modules
    env_file:
      - .env
    command: npm run start:dev
    links:
      - mysql

  mysql:
    container_name: my-mysql-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always     
    environment:
      MYSQL_DATABASE: wit
      MYSQL_ROOT_USERNAME: root
    ports:
      - '3306:3306' 
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql_data:
